### ISSUE TITLE
How long does this demo take to process a face image?

### ISSUE THREAD

**Issue by anleleaaa** [P2Oileen/oh-my-face#1]
How long does this demo take to process a face image?

**Comment by P2Oileen** [comment]
Hi anleleaaa! Thank you for your attention, but sorry, this repo is a long time ago, I didn't try to measure the speed at that time. You can use the notebook in [colab](https://colab.research.google.com/github/P2Oileen/oh-my-face/blob/main/oh-my-face.ipynb) provided to run this repo, which is a simple method. You can do any speed tests inside.
FYI, the running time of this repo can be roughly calculated as the sum of the time of the three models of [StyleCLIP](https://github.com/orpatashnik/StyleCLIP)+[RIFE](https://github.com/megvii-research/ECCV2022-RIFE)+[encoder4editing](https://github.com/omertov/encoder4editing). You can view the reported times in the original papers for these three jobs.
Hope that answers your questions!

**Comment by anleleaaa** [comment]
> 
I want a faster one, about 5 seconds, input a face picture, and then input a key point of facial expression (or segmented face mask) to output the same identity facial expression. Is there any recommendation for this kind of demo? Thank you very much
